version: '3.7'

services:
  httpd:
    build:
      context: .docker/httpd
    restart: always
    container_name: wp-apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/app
    networks:
      - wp-network
  php-fpm:
    build:
      context: .docker/php-fpm
    environment:
      DB_NAME: wp
      WP_DEBUG: 1
    restart: always
    container_name: wp-php
    volumes:
      - ./:/var/app
    networks:
      - wp-network
  mysql:
    build:
      context: .docker/mysql
    restart: always
    container_name: wp-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: wp
    volumes:
      - db_data:/var/lib/mysql:rw
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  db_data: